config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  # root 'events#index'
  # resources :events


  get '/events/:id', to: 'home#index'
  get '/new_event', to: 'home#index'
  get '/confirm', to: 'home#index'

  namespace :api do
    resources :events
  end

  namespace :admin do
    resources :events
  end

  # match '*path', to: 'home#index', via: :all
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  include ActiveModel::Serializers::JSON

  after_validation :set_slug, only: [:create, :update]
  has_one_attached :photo

  validates_presence_of :title, :location, :date, :link, :summary, :description

  def to_param
    "#{id}-#{slug}"
  end

  def attributes
    {
      'id' => nil,
      'title' => nil,
      'location' => nil,
      'date' => nil,
      'link' => nil,
      'summary' => nil,
      'description' => nil,
      'updated_at' => nil,
      'created_at' => nil,
      'attachment_url' => nil
    }
  end

  def attachment_url
    if photo.attached?
      Rails.application.routes.url_helpers.rails_representation_url(
        photo.variant(resize_to_limit: [350, 240]).processed, only_path: true
      )
    end
  end

  private

  def set_slug
    self.slug = title.to_s.parameterize
  end

end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController
  layout 'admin'
  http_basic_authenticate_with name: "tyshaikh", password: "staples1951"
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index
    @events = Event.all.sort_by &:date
  end

  def show
  end

  def new
    @event = Event.new
  end

  def edit
  end

  def create
    @event = Event.new(event_params)

    if @event.save
      redirect_to admin_events_path
    else
      render 'new'
    end
  end

  def update
    if @event.update(event_params)
      redirect_to admin_events_path
    else
      render 'edit'
    end
  end

  def destroy
    @event.destroy

    redirect_to admin_events_path
  end

  private

  def event_params
    params.require(:event).permit(:title, :location, :date, :link, :summary, :description, :photo)
  end

  def set_event
    @event = Event.find(params[:id])
  end

end

app/controllers/api/events_controller.rb
class API::EventsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index
    @events = Event.all
    json_response(@events)
  end

  def show
    json_response(@event)
  end

  def new
    @event = Event.new
    json_response(@event)
  end

  def edit
    json_response(@event)
  end

  def create
    @event = Event.create!(event_params)
    json_response(@event, :created)
  end

  def update
    @event.update(event_params)
    head :no_content
    # json_response(@event)
  end

  def destroy
    @event.destroy
    head :no_content
  end

  private

  def event_params
    params.permit(:title, :location, :date, :link, :summary, :description, :photo)
  end

  def set_event
    @event = Event.find(params[:id])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
  include Response
  include ExceptionHandler
end

app/controllers/concerns/exception_handler.rb
# app/controllers/concerns/exception_handler.rb
module ExceptionHandler
  # provides the more graceful `included` method
  extend ActiveSupport::Concern

  included do
    rescue_from ActiveRecord::RecordNotFound do |e|
      json_response({ message: e.message }, :not_found)
    end

    rescue_from ActiveRecord::RecordInvalid do |e|
      json_response({ message: e.message }, :unprocessable_entity)
    end
  end
end

app/controllers/concerns/response.rb
# app/controllers/concerns/response.rb
module Response
  def json_response(object, status = :ok)
    render json: object, status: status
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index
    @events = Event.all.sort_by &:date
    # @groups = Event.all.group_by { |e| e.date.beginning_of_month }
  end

  def show
  end

  def new
    @event = Event.new
  end

  def edit
  end

  def create
    @event = Event.new(event_params)

    if @event.save
      redirect_to @event
    else
      render 'new'
    end
  end

  def update
    if @event.update(event_params)
      redirect_to @event
    else
      render 'edit'
    end
  end

  def destroy
    @event.destroy

    redirect_to events_path
  end

  private

  def event_params
    params.require(:event).permit(:title, :location, :date, :link, :summary, :description, :photo)
  end

  def set_event
    @event = Event.find(params[:id])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/admin/events/404.html.erb
<section class="mt-24">
  <div class="text-center">
    <div class="text-4xl font-bold mb-2">
      Oh no!
    </div>
    <div class="text-xl text-gray-600 mb-8 max-w-3xl m-auto">
      We can't seem to find the page you're looking for.
    </div>
    <a href="/" class="text-blue-500 underline">Home page</a>
  </div>

app/views/admin/events/_event.html.erb
<section class="mt-8 w-2/3 mx-auto">
  <div class="flex items-center justify-between rounded shadow bg-white mb-8 p-5">
    <div class="px-8 mb-4">
      <p class="text-blue-600 font-bold leading-wide uppercase text-gray-600 text-xl lg:text-base mb-1">
        <%= event.date.strftime("%B %-d, %Y") %>
      </p>
      <p class="font-semibold text-3xl lg:text-2xl mb-1">
        <%= event.title %>
      </p>
      <p class="text-gray-600 text-xl lg:text-base">
        <%= event.location %>
      </p>
    </div>
    <div class="w-1/3">
      <div class="inline-block">
        <%= link_to edit_admin_event_path(event) do %>
          <button class="bg-blue-500 hover:bg-blue-700 text-2xl lg:text-base text-white font-bold py-2 px-4 rounded">
            Edit
          </button>
        <% end %>
      </div>

      <div class="inline-block">
        <form method="POST" action="/admin/events/<%= event.id %>" onsubmit="return confirm('Are you sure you want to delete this job?');">
          <div style="margin:0;padding:0">
            <input name="_method" value="delete" type="hidden" />
            <button class="bg-blue-500 hover:bg-blue-700 text-2xl lg:text-base text-white font-bold py-2 px-4 rounded" type="submit">Delete</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>

app/views/admin/events/_form.html.erb
<%= form_with model: [:admin, @event] do |form| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@event.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @event.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="w-full">
    <div class="pt-6 pb-4">

      <div class="mb-4">
        <label class="block text-gray-700 lg:text-sm font-bold mb-2">
          Event Title
        </label>
        <%= form.text_field :title, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline", placeholder: "ODSC Conference 2020", required: true %>
        <p class="text-gray-600 text-sm lg:text-xs italic">Please specify a title for the event.</p>
      </div>

      <!-- Event date -->
      <div class="mb-4">
        <label class="block text-gray-700 lg:text-sm font-bold mb-2">
          Event Date
        </label>
        <%= form.date_field :date, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline", required: true %>
        <p class="text-gray-600 text-sm lg:text-xs italic">Please specify the date of the event.</p>
      </div>

      <!-- Event location -->
      <div class="mb-4">
        <label class="block text-gray-700 lg:text-sm font-bold mb-2">
          Event Location
        </label>
        <%= form.text_field :location, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline", placeholder: "Virtual", required: true %>
        <p class="text-gray-600 text-sm lg:text-xs italic">Please specify the city, state or country. If virtual, simply put "Virtual" or "Remote".</p>
      </div>

      <div class="mb-4">
        <label class="block text-gray-700 lg:text-sm font-bold mb-2">
          Event Graphic <span class="text-gray-600, text-xs font-light">(optional)</span>
        </label>
        <%= form.file_field :photo, class: "appearance-none border-2 border-gray-300 rounded w-full py-2 px-4 mb-3 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-gray-500", accept: "image/jpg, image/jpeg, image/png, image/gif, image/tiff, image/tif, image/svg" %>
        <p class="text-gray-600 text-xs italic">Please make sure the file is less than 1 MB and is either a JPG or PNG file.</p>
      </div>

      <div class="mb-4">
        <label class="block text-gray-700 lg:text-sm font-bold mb-2">
          Event Website
        </label>
        <%= form.url_field :link, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline", required: true %>
        <p class="text-gray-600 text-sm lg:text-xs italic">You can link to a ticketing page or another website.</p>
      </div>

      <div class="mb-4">
        <label class="block text-gray-700 lg:text-sm font-bold mb-2">
          Event Summary
        </label>
        <%= form.text_area :summary, rows: 4, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline" %>
        <p class="text-gray-600 text-sm lg:text-xs italic mt-2">Provide a short summary of the event.</p>
      </div>

      <div class="mb-4">
        <label class="block text-gray-700 lg:text-sm font-bold mb-2">
          Event Description
        </label>
        <%= form.text_area :description, rows: 10, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline" %>
        <p class="text-gray-600 text-sm lg:text-xs italic mt-2">Provide a long description of the event.</p>
      </div>

    </div>
  </div>
  <div class="flex items-center justify-between">
    <%= form.submit (@event.new_record? ? "Submit event" : "Update event"), class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
    <%= link_to 'Go back', admin_events_path, class: "bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded" %>
  </div>
<% end %>

app/views/admin/events/edit.html.erb
<div class="rounded shadow my-8 bg-white w-full lg:w-2/3 p-10 mx-auto">
  <div class="font-bold text-2xl text-center">
    Edit an existing event
  </div>
  <%= render 'form' %>
</div>


<script>
  // Setup toolbar options
  var toolbarOptions = [
    [{ 'header': [1, 2, 3, false] }],
    ['bold', 'italic', 'underline'],        // toggled buttons

    // [{ 'header': 1 }, { 'header': 2 }],               // custom button values
    [{ 'list': 'ordered'}, { 'list': 'bullet' }],

    ['clean']                                         // remove formatting button
  ];

  // Initialize editor
  var quill = new Quill('#editor', {
    modules: {
      toolbar: toolbarOptions
    },
    theme: 'snow'
  });

  // Update hidden field
  const hidden = document.querySelector('#hiddenArea');
  let quillVal = quill.container.firstChild.innerHTML;
  hidden.value = quillVal;

  quill.on('text-change', function() {
    let quillVal = quill.container.firstChild.innerHTML;
    hidden.value = quillVal;
  });
</script>

<style>
  #editor {
    height: 350px;
  }
</style>

app/views/admin/events/index.html.erb
<section class="mt-10">
  <div class="text-center">
    <%= link_to new_admin_event_path do %>
      <button class="bg-blue-500 hover:bg-blue-700 text-2xl lg:text-base text-white font-bold py-2 px-4 rounded">
        Add a new event
      </button>
    <% end %>
  </div>
</section>

<section class="mt-10">
  <div class="">
    <p class="text-xl uppercase text-gray-700 font-semibold text-center tracking-widest">
      All Events
    </p>
  </div>

  <% @events.each do |event| %>
    <%= render event %>
  <% end %>
</section>

app/views/admin/events/new.html.erb
<div class="rounded shadow my-8 bg-white w-full lg:w-2/3 p-10 mx-auto">
  <div class="font-bold text-2xl text-center">
    Add a new event
  </div>
  <%= render 'form' %>
</div>

<script>
  // Setup toolbar options
  var toolbarOptions = [
    [{ 'header': [1, 2, 3, false] }],
    ['bold', 'italic', 'underline'],        // toggled buttons

    // [{ 'header': 1 }, { 'header': 2 }],               // custom button values
    [{ 'list': 'ordered'}, { 'list': 'bullet' }],

    ['clean']                                         // remove formatting button
  ];

  // Initialize editor
  var quill = new Quill('#editor', {
    modules: {
      toolbar: toolbarOptions
    },
    theme: 'snow'
  });

  // Update hidden field
  const hidden = document.querySelector('#hiddenArea');
  let quillVal = quill.container.firstChild.innerHTML;
  hidden.value = quillVal;

  quill.on('text-change', function() {
    let quillVal = quill.container.firstChild.innerHTML;
    hidden.value = quillVal;
  });
</script>

<style>
  #editor {
    height: 350px;
  }
</style>

app/views/admin/events/show.html.erb
<section class="my-8 w-full mx-auto">
  <div>
    <p class="text-red-500 font-semibold">
      <%= link_to '&larr; Back to all events'.html_safe, admin_events_path, class: "" %>
    </p>
  </div>
</section>

<%= render @event %>

<section class="mt-16">
  <div class="my-8">
    <p class="text-xl uppercase text-gray-700 font-semibold tracking-widest">
      Event Details
    </p>
  </div>
  <div class="flex items-center rounded shadow bg-white mb-8 p-5">
    <div class="p-8">
      <p class="text-xl lg:text-lg">
        <%= @event.description.html_safe %>
      </p>
    </div>
  </div>
  <div class="">
    <%= link_to @event.link, target: '_blank' do %>
      <button class="bg-blue-500 hover:bg-blue-700 text-2xl lg:text-base text-white font-bold py-2 px-4 rounded">
        Learn more
      </button>
    <% end %>
  </div>
</section>

app/views/events/404.html.erb
<section class="mt-24">
  <div class="text-center">
    <div class="text-4xl font-bold mb-2">
      Oh no!
    </div>
    <div class="text-xl text-gray-600 mb-8 max-w-3xl m-auto">
      We can't seem to find the page you're looking for.
    </div>
    <a href="/" class="text-blue-500 underline">Home page</a>
  </div>

app/views/events/_event.html.erb
<section class="mt-8">
  <div class="flex items-center rounded shadow bg-white mb-8 p-5">
    <%= image_tag (event.photo.attached? ? event.photo.variant(resize_to_limit: [350, 240]) : "conf-generic.jpeg"), class: "w-1/3 rounded mr-10" %>
    <div class="px-8">
      <div class="mb-4">
        <p class="text-blue-600 font-bold leading-wide uppercase text-gray-600 text-xl lg:text-base mb-1">
          <%= event.date.strftime("%B %-d, %Y") %>
        </p>
        <p class="font-semibold text-3xl lg:text-2xl mb-1">
          <%= event.title %>
        </p>
        <p class="text-gray-600 text-xl lg:text-base">
          <%= event.location %>
        </p>
      </div>
      <p class="text-xl lg:text-base">
        <%= event.summary %>
      </p>
    </div>
  </div>
</section>

app/views/events/_form.html.erb
<%= form_with model: @event do |form| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@event.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @event.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="w-full">
    <div class="pt-6 pb-4">

      <div class="mb-4">
        <label class="block text-gray-700 lg:text-sm font-bold mb-2">
          Event Title
        </label>
        <%= form.text_field :title, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline", placeholder: "ODSC Conference 2020", required: true %>
        <p class="text-gray-600 text-sm lg:text-xs italic">Please specify a title for the event.</p>
      </div>

      <!-- Event date -->
      <div class="mb-4">
        <label class="block text-gray-700 lg:text-sm font-bold mb-2">
          Event Date
        </label>
        <%= form.date_field :date, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline", required: true %>
        <p class="text-gray-600 text-sm lg:text-xs italic">Please specify the date of the event.</p>
      </div>

      <!-- Event location -->
      <div class="mb-4">
        <label class="block text-gray-700 lg:text-sm font-bold mb-2">
          Event Location
        </label>
        <%= form.text_field :location, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline", placeholder: "Virtual", required: true %>
        <p class="text-gray-600 text-sm lg:text-xs italic">Please specify the city, state or country. If virtual, simply put "Virtual" or "Remote".</p>
      </div>

      <div class="mb-4">
        <label class="block text-gray-700 lg:text-sm font-bold mb-2">
          Event Graphic <span class="text-gray-600, text-xs font-light">(optional)</span>
        </label>
        <%= form.file_field :photo, class: "appearance-none border-2 border-gray-300 rounded w-full py-2 px-4 mb-3 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-gray-500", accept: "image/jpg, image/jpeg, image/png, image/gif, image/tiff, image/tif, image/svg" %>
        <p class="text-gray-600 text-xs italic">Please make sure the file is less than 1 MB and is either a JPG or PNG file.</p>
      </div>

      <div class="mb-4">
        <label class="block text-gray-700 lg:text-sm font-bold mb-2">
          Event Website
        </label>
        <%= form.url_field :link, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline", required: true %>
        <p class="text-gray-600 text-sm lg:text-xs italic">You can link to a ticketing page or another website.</p>
      </div>

      <div class="mb-4">
        <label class="block text-gray-700 lg:text-sm font-bold mb-2">
          Event Summary
        </label>
        <%= form.text_area :summary, rows: 4, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline" %>
        <p class="text-gray-600 text-sm lg:text-xs italic mt-2">Provide a short summary of the event.</p>
      </div>

      <div class="mb-4">
        <label class="block text-gray-700 lg:text-sm font-bold mb-2">
          Event Description
        </label>
        <%= form.text_area :description, rows: 10, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline" %>
        <p class="text-gray-600 text-sm lg:text-xs italic mt-2">Provide a long description of the event.</p>
      </div>

    </div>
  </div>
  <div class="flex items-center justify-between">
    <%= form.submit (@event.new_record? ? "Submit event" : "Update event"), class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
    <%= link_to 'Go back', events_path, class: "bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded" %>
  </div>
<% end %>

app/views/events/edit.html.erb
<div class="rounded shadow my-8 bg-white w-full lg:w-2/3 p-10 mx-auto">
  <div class="font-bold text-2xl text-center">
    Edit an existing event
  </div>
  <%= render 'form' %>
</div>


<script>
  // Setup toolbar options
  var toolbarOptions = [
    [{ 'header': [1, 2, 3, false] }],
    ['bold', 'italic', 'underline'],        // toggled buttons

    // [{ 'header': 1 }, { 'header': 2 }],               // custom button values
    [{ 'list': 'ordered'}, { 'list': 'bullet' }],

    ['clean']                                         // remove formatting button
  ];

  // Initialize editor
  var quill = new Quill('#editor', {
    modules: {
      toolbar: toolbarOptions
    },
    theme: 'snow'
  });

  // Update hidden field
  const hidden = document.querySelector('#hiddenArea');
  let quillVal = quill.container.firstChild.innerHTML;
  hidden.value = quillVal;

  quill.on('text-change', function() {
    let quillVal = quill.container.firstChild.innerHTML;
    hidden.value = quillVal;
  });
</script>

<style>
  #editor {
    height: 350px;
  }
</style>

app/views/events/index.html.erb
<section class="mt-10">
  <div class="text-center">
    <div class="text-6xl font-bold mb-2">
      Data Science Conferences
    </div>
    <div class="text-3xl lg:text-2xl text-gray-600 mb-6 max-w-3xl m-auto">
      Find out about upcoming data science conferences around the world.
    </div>
    <%= link_to new_event_path do %>
      <button class="bg-blue-500 hover:bg-blue-700 text-2xl lg:text-base text-white font-bold py-2 px-4 rounded">
        Submit an event
      </button>
    <% end %>
  </div>
</section>

<section class="mt-16">
  <div class="">
    <p class="text-xl uppercase text-gray-700 font-semibold text-center tracking-widest">
      Upcoming Events
    </p>
  </div>

  <% @events.each do |event| %>
    <%= link_to event_path(event) do %>
      <%= render event %>
    <% end %>
  <% end %>
</section>

app/views/events/new.html.erb
<div class="rounded shadow my-8 bg-white w-full lg:w-2/3 p-10 mx-auto">
  <div class="font-bold text-2xl text-center">
    Add a new event
  </div>
  <%= render 'form' %>
</div>

<script>
  // Setup toolbar options
  var toolbarOptions = [
    [{ 'header': [1, 2, 3, false] }],
    ['bold', 'italic', 'underline'],        // toggled buttons

    // [{ 'header': 1 }, { 'header': 2 }],               // custom button values
    [{ 'list': 'ordered'}, { 'list': 'bullet' }],

    ['clean']                                         // remove formatting button
  ];

  // Initialize editor
  var quill = new Quill('#editor', {
    modules: {
      toolbar: toolbarOptions
    },
    theme: 'snow'
  });

  // Update hidden field
  const hidden = document.querySelector('#hiddenArea');
  let quillVal = quill.container.firstChild.innerHTML;
  hidden.value = quillVal;

  quill.on('text-change', function() {
    let quillVal = quill.container.firstChild.innerHTML;
    hidden.value = quillVal;
  });
</script>

<style>
  #editor {
    height: 350px;
  }
</style>

app/views/events/show.html.erb
<section class="my-8 w-full mx-auto">
  <div>
    <p class="text-red-500 font-semibold">
      <%= link_to '&larr; Back to all events'.html_safe, events_path, class: "" %>
    </p>
  </div>
</section>

<%= render @event %>

<section class="mt-16">
  <div class="my-8">
    <p class="text-xl uppercase text-gray-700 font-semibold tracking-widest">
      Event Details
    </p>
  </div>
  <div class="flex items-center rounded shadow bg-white mb-8 p-5">
    <div class="p-8">
      <p class="text-xl lg:text-lg">
        <%= @event.description.html_safe %>
      </p>
    </div>
  </div>
  <div class="">
    <%= link_to @event.link, target: '_blank' do %>
      <button class="bg-blue-500 hover:bg-blue-700 text-2xl lg:text-base text-white font-bold py-2 px-4 rounded">
        Learn more
      </button>
    <% end %>
  </div>
</section>

app/views/home/index.html.erb
<%= javascript_pack_tag 'index' %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Events Admin</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <% stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' -%>
    <% javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' -%>
    <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">

    <style>
      #menu-toggle:checked + #menu {
        display: block;
      }
    </style>

  </head>

  <body class="bg-gray-200">

    <nav class=" bg-gray-500 p-6">
      <div class="flex items-center justify-between flex-wrap w-3/4 mx-auto">
        <div class="flex items-center flex-shrink-0 text-white mr-6">
          <span class="font-semibold tracking-tight">Event Listing</span>
        </div>

        <label for="menu-toggle" class="cursor-pointer lg:hidden block">
          <div class="flex items-center px-3 py-2 border rounded text-teal-200 border-teal-400 hover:text-white hover:border-white">
            <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
          </div>

        </label>
        <input type="checkbox" class="hidden" id="menu-toggle" />

        <div class="hidden flex-grow lg:flex lg:items-center lg:w-auto w-full" id="menu">
          <div class="text-sm lg:flex-grow">
            <a href="/admin/events" class="block mt-4 lg:inline-block lg:mt-0 text-gray-200 hover:text-white mr-4">
              Dashboard
            </a>
          </div>

          <!-- <div>
            <form method="POST" action="/logout">
              <button class="inline-block text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-gray-600 hover:bg-white focus:outline-none focus:shadow-outline mt-4 lg:mt-0" type="submit">
                Logout
              </button>
            </form>
          </div> -->

        </div>
      </div>
    </nav>

    <div class="container mx-auto text-gray-700 h-screen">
      <%= yield %>
    </div>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Events</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%# stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Quill JS -->
    <link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">
    <script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>

  </head>

  <body class="bg-gray-100">

    <div class="container mx-auto w-full lg:w-3/4">
      <%= yield %>
    </div>


  </body>

</html>